import { useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Download, Share2, FileOutput, FileBarChart, ArrowRight } from 'lucide-react'
import PageHeader from '../components/ui/PageHeader'
import Card from '../components/ui/Card'
import Button from '../components/ui/Button'
import { RiskBadge } from '../components/ui/StatusBadge'
import { ClaimStatusBadge } from '../components/ui/StatusBadge'
import RiskGauge from '../components/ui/RiskGauge'
import { companies, getCompanyById } from '../data/companies'
import { useToast } from '../hooks/useToast'

export default function ReportsPage() {
  const { companyId } = useParams()
  const navigate = useNavigate()
  const { push } = useToast()
  const [downloaded, setDownloaded] = useState(false)

  if (!companyId) {
    return (
      <div className="animate-fade-in">
        <PageHeader
          eyebrow="Report Generation"
          title="Reports"
          subtitle="Generate a complete sustainability verification report for any analyzed company."
        />
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {companies.map((c) => (
            <Card key={c.id} hoverable className="cursor-pointer" onClick={() => navigate(`/reports/${c.id}`)}>
              <div className="flex items-center gap-3">
                <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-emerald-500/15 text-sm font-bold text-emerald-400">
                  {c.logoInitials}
                </span>
                <div className="min-w-0">
                  <p className="truncate font-bold text-white">{c.name}</p>
                  <p className="text-xs text-navy-500">{c.sector}</p>
                </div>
              </div>
              <div className="mt-4 flex items-center justify-between">
                <RiskBadge level={c.riskLevel} />
                <span className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-400">
                  Generate <ArrowRight className="h-3.5 w-3.5" />
                </span>
              </div>
            </Card>
          ))}
        </div>
      </div>
    )
  }

  const company = getCompanyById(companyId)
  if (!company) {
    navigate('/reports')
    return null
  }

  function handleAction(action: string) {
    if (action === 'Download PDF') setDownloaded(true)
    push({ kind: 'success', title: `${action} triggered`, message: `This is a simulated ${action.toLowerCase()} action for the prototype.` })
  }

  return (
    <div className="mx-auto max-w-4xl animate-fade-in">
      <PageHeader
        eyebrow="Sustainability Verification Report"
        title={company.name}
        subtitle={`Analysis Period: ${company.analysisPeriod} · Generated by GREENWATCH AI`}
        actions={
          <div className="flex gap-2">
            <Button variant="secondary" size="sm" onClick={() => handleAction('Share Report')}>
              <Share2 className="h-3.5 w-3.5" /> Share Report
            </Button>
            <Button variant="secondary" size="sm" onClick={() => handleAction('Export Evidence')}>
              <FileOutput className="h-3.5 w-3.5" /> Export Evidence
            </Button>
            <Button size="sm" onClick={() => handleAction('Download PDF')}>
              <Download className="h-3.5 w-3.5" /> {downloaded ? 'Downloaded' : 'Download PDF'}
            </Button>
          </div>
        }
      />

      <Card className="mb-4 flex items-center gap-3 border-navy-800 bg-navy-900 text-white">
        <FileBarChart className="h-5 w-5 text-emerald-400" />
        <p className="text-sm font-semibold">GREENWATCH AI &mdash; SUSTAINABILITY VERIFICATION REPORT</p>
      </Card>

      <Card className="mb-4">
        <h2 className="text-sm font-bold uppercase tracking-wide text-navy-500">1. Executive Summary</h2>
        <p className="mt-2 text-sm leading-relaxed text-navy-500">{company.summary}</p>
      </Card>

      <Card className="mb-4">
        <h2 className="mb-3 text-sm font-bold uppercase tracking-wide text-navy-500">2. Greenwashing Risk Score</h2>
        <div className="flex flex-col items-center gap-4 sm:flex-row sm:justify-around">
          <RiskGauge score={company.riskScore} size={180} />
          <div className="text-center sm:text-left">
            <p className="text-sm text-navy-500">AI Confidence</p>
            <p className="text-2xl font-extrabold text-white">{company.aiConfidence}%</p>
            <div className="mt-2"><RiskBadge level={company.riskLevel} /></div>
          </div>
        </div>
      </Card>

      <Card className="mb-4">
        <h2 className="mb-3 text-sm font-bold uppercase tracking-wide text-navy-500">3. Claims Analysis</h2>
        <div className="space-y-3">
          {company.claims.map((claim) => (
            <div key={claim.id} className="flex items-start justify-between gap-3 border-b border-white/[0.06] pb-3 last:border-0 last:pb-0">
              <div>
                <p className="text-xs font-bold text-navy-500">{claim.code}</p>
                <p className="text-sm text-navy-200">&ldquo;{claim.text}&rdquo;</p>
              </div>
              <ClaimStatusBadge status={claim.status} className="shrink-0" />
            </div>
          ))}
        </div>
      </Card>

      <Card className="mb-4">
        <h2 className="text-sm font-bold uppercase tracking-wide text-navy-500">4. Evidence Analysis</h2>
        <p className="mt-2 text-sm text-navy-500">{company.evidence.length} evidence points collected across financial, environmental, and certification sources.</p>
      </Card>

      <Card className="mb-4">
        <h2 className="text-sm font-bold uppercase tracking-wide text-navy-500">5. Emission Analysis</h2>
        <p className="mt-2 text-sm text-navy-500">{company.emissions.note}</p>
      </Card>

      <Card className="mb-4">
        <h2 className="text-sm font-bold uppercase tracking-wide text-navy-500">6. Financial Alignment</h2>
        <p className="mt-2 text-sm text-navy-500">{company.financials.finding}</p>
      </Card>

      <Card className="mb-4">
        <h2 className="text-sm font-bold uppercase tracking-wide text-navy-500">7. Certification Verification</h2>
        <p className="mt-2 text-sm text-navy-500">
          {company.certifications.filter((c) => c.verified).length} of {company.certifications.length} claimed certifications verified.
        </p>
      </Card>

      <Card className="mb-4">
        <h2 className="text-sm font-bold uppercase tracking-wide text-navy-500">8. Industry Benchmark</h2>
        <p className="mt-2 text-sm text-navy-500">
          Ranked against {company.sector} sector peers across emission intensity, renewable use, disclosure quality, and sustainability investment.
        </p>
      </Card>

      <Card className="mb-4">
        <h2 className="text-sm font-bold uppercase tracking-wide text-navy-500">9. Risk Factors</h2>
        <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-navy-500">
          {company.scoreDrivers
            .filter((d) => d.value >= 40)
            .map((d) => (
              <li key={d.key}>{d.label}: {d.value}/100</li>
            ))}
        </ul>
      </Card>

      <Card className="mb-8">
        <h2 className="text-sm font-bold uppercase tracking-wide text-navy-500">10. Recommended Actions</h2>
        <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-navy-500">
          {company.recommendedActions.map((a) => (
            <li key={a.id}>{a.text}</li>
          ))}
        </ul>
      </Card>
    </div>
  )
}
